Repository pyOpenSci/pyosMeta, pull requests merged in 2024-03, with the labels that each got.

#120 Fix: refactor and reorganize modules
  CHANGELOG.md
  src/pyosmeta/__init__.py
  src/pyosmeta/clean.py
  src/pyosmeta/cli/update_contributors.py
  src/pyosmeta/cli/update_review_teams.py
  src/pyosmeta/contributors.py
  src/pyosmeta/models.py
  src/pyosmeta/parse_issues.py
  tests/integration/parse_issues.py
  tests/unit/test_parse_categories.py
  tests/unit/test_parse_user_names.py
  tests/unit/test_review_model.py
Labels: refactor

#128 Update github actions to resolve nodejs 16 warnings
  .github/workflows/publish-pypi.yml
  .github/workflows/run-script.yml
Labels: maintenance

#127 Split utilities test file into two to match the source files
  tests/unit/test_utils_clean.py
  tests/unit/test_utils_parse.py
Labels: maintenance, refactor

#126 Refactor cleaning utility input names to be consistent and update docstrings
  src/pyosmeta/utils_clean.py
Labels: maintenance, refactor

#147 Add changelog for v0.2.4
  CHANGELOG.md
Labels: release
